export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_CART = "ADD_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY="DECREASE_QUANTITY";
export const DELETE_CART = "DELETE_CART";
export const DETAIL_PRODUCT = "DETAIL_PRODUCT";
export const APPLY_COUPON  = "APPLY_COUPON" ;
export const APPLY_COUPONS_DATA = "APPLY_COUPONS_DATA";
export const SET_SIPPING = "SET_SIPPING";
export const ORDER = "ORDER";
export const CONTRY="CONTRY";
export const PAYMENT_METHOD = "PAYMENT_METHOD"
export const SHIPPING_LINESDATA="SHIPPING_LINESDATA";
export const ORDERRECIVED = "ORDERRECIVED";



